version: '3.5'

networks:
  d3-back-office:
    name: d3-${SUBNET}
    attachable: true

services:
  d3-iroha:
    image: hyperledger/iroha@sha256:e025a0f340ee4782115691f0836f7cc4c548a5cc0ba1f6e3990c9a27ee79625f
    container_name: d3-iroha-${SUBNET}
    depends_on:
      - d3-iroha-postgres
    tty: true
    environment:
      - KEY=keys/node0
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    networks:
      - d3-back-office
    volumes:
      - ./iroha:/opt/iroha_data
    logging:
      driver: none

  d3-iroha-postgres:
    image: postgres:9.5
    container_name: d3-iroha-postgres-${SUBNET}
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - d3-back-office
    logging:
      driver: none

  grpcwebproxy:
    build:
      context: grpcwebproxy/
    container_name: d3-grpcwebproxy-${SUBNET}
    depends_on:
      - d3-iroha
    entrypoint:
      - grpcwebproxy
      - --backend_addr=d3-iroha:50051
      - --run_tls_server=false
    networks:
      - d3-back-office
    logging:
      driver: none
    # ports:
    #   - 8081:8080

  d3-back-office:
    build:
      context: back-office
    container_name: d3-back-office-${SUBNET}
    depends_on:
      - grpcwebproxy
    networks:
      - d3-back-office
    volumes:
      - ..:/app
      # - /dev/null:/app/node_modules
